### ISSUE TITLE
error destroying

### ISSUE THREAD

**Issue by txsneakerhead23** [ryan9918/digitaloceandestroyer#1]
get this error

destroy all droplets? (y/n):   y
Traceback (most recent call last):
  File "destroyer.py", line 18, in <module>
    choice = input("destroy all droplets? (y/n):   ")
  File "<string>", line 1, in <module>
NameError: name 'y' is not defined

**Comment by ryan9918** [comment]
make sure you are running in python 3. If you have python 3 installed make sure to do python3 destroyer.py, otherwise please install python3
